/*
 * Program: EECS 348 Assignment 3
 * Description: C++ program that prioritizes a CEO's emails using a MaxHeap.
 *              Emails are prioritized first by sender category and then by date.
 *              The program uses object-oriented classes to represent emails,
 *              manage the MaxHeap, manage the email queue, and process commands.
 * Inputs: EMAIL, NEXT, READ, and COUNT commands read from a test file
 *         provided through the command line or from standard input.
 * Outputs: Displays the next highest-priority email and the current number
 *          of unread emails when requested.
 * Usage: ./assignment3 sample_test.txt
 *        or ./assignment3 < sample_test.txt
 * Collaborators: None
 * Other Sources: Claude (original C++ code selected as the basis for this assignment),
 *                Gemini (second GenAI program used for comparison),
 *                ChatGPT (assistance with prompting, analysis, testing,
 *                detailed comments, source attribution, and revisions)
 * Author: Nathan Lenahan
 * Creation Date: September 30, 2026
 * Revision Date: October 1, 2026
 * Revisions: 
 * - Added detailed comments and source attribution to the original Claude-generated code. 
 * - Revised input handling to support both command-line test files and standard input.
 * - Edited removeMax() to avoid unnecessary heap operations when removing the final email.
 * - Improved COUNT output formatting when exactly one email remains. 
 * - Made Email data members private and added read-only getter methods to improve encapsulation.
 * - Revised peekMax() to safely handle an empty heap by returning nullptr.
 * - Replaced endl with newline characters to avoid unnecessary output stream flushes.
 * - Stored the unread-email count in a local variable so heap.size() is only called once in showCount().
 * - Removed the unused isEmpty() method after peekMax() was revised to handle empty heaps directly.
 * - Added an output message when READ is used with no emails remaining.
 */


// The following include statements are from the original code generated by Claude
#include <iostream> // Provides standard input and output using cin and cout
#include <string> // Provides the string data type and string operations
#include <fstream> // Provides file input using ifstream

using namespace std; // Allows standard library names to be used without the std:: prefix

// The following Email class is based on the original code generated by Claude
// Its data members were revised to be private for better encapsulation, with help from ChatGPT
// The class stores one email and contains the logic needed to determine its priority
class Email { // Starts the Email class

private: // Prevents other classes from directly modifying the Email object's stored data

    string sender; // Stores the sender category of the email
    string subject; // Stores the subject line of the email
    string date; // Stores the original date in MM-DD-YYYY format

    int senderRank; // Stores the numerical priority of the sender category
    int dateKey; // Stores the date as YYYYMMDD so dates can be compared numerically
    int sequence; // Stores arrival order and is used to break exact priority ties


public: // Makes the following constructors and public methods accessible outside the Email class

    // The following default Email constructor is from the original code generated by Claude
    // It creates an empty Email object with default values
    Email() // Starts the default Email constructor
        : sender(""), subject(""), date(""), // Initializes all string fields as empty
          senderRank(0), dateKey(0), sequence(0) {} // Initializes all integer fields to 0


    // The following parameterized Email constructor is from the original code generated by Claude
    // It creates an Email object using the sender, subject, date, and arrival sequence
    Email(const string& s, const string& subj, const string& d, int seq) // Starts the parameterized Email constructor
        : sender(s), subject(subj), date(d), sequence(seq) { // Stores the provided email information

        senderRank = rankFor(s); // Converts the sender category into its numerical priority
        dateKey = keyFor(d);     // Converts the date into YYYYMMDD format for comparison
    } // Ends the parameterized Email constructor

    // The following hasHigherPriorityThan method is from the original code generated by Claude
    // It returns true when this Email should be read before the other Email
    bool hasHigherPriorityThan(const Email& other) const { // Starts the priority comparison

        if (senderRank != other.senderRank) { // Checks whether the sender priorities are different
            return senderRank > other.senderRank; // Higher sender rank means higher priority
        } // Ends the sender-priority comparison

        if (dateKey != other.dateKey) { // Runs when sender priorities match but dates are different
            return dateKey > other.dateKey; // Newer date receives higher priority
        } // Ends the date comparison

        return sequence < other.sequence; // Earlier arrival wins when sender and date are identical
    } // Ends the hasHigherPriorityThan method

    // The following getter methods were added to the Claude-based Email class with help from ChatGPT
    // They provide read-only access to the Email information while keeping the data members private
    const string& getSender() const { // Starts the method that provides access to the sender
        return sender; // Returns a read-only reference to the Email's sender category
    } // Ends the getSender method
    const string& getSubject() const { // Starts the method that provides access to the subject
        return subject; // Returns a read-only reference to the Email's subject line
    } // Ends the getSubject method
    const string& getDate() const { // Starts the method that provides access to the date
        return date; // Returns a read-only reference to the Email's original date
    } // Ends the getDate method

private: // Makes the following helper methods usable only inside the Email class

    // The following rankFor method is from the original code generated by Claude
    // It converts each sender category into its required numerical priority
    static int rankFor(const string& s) { // Starts the sender-priority conversion

        if (s == "Boss")            return 5; // Gives Boss the highest priority
        if (s == "Subordinate")     return 4; // Gives Subordinate the second-highest priority
        if (s == "Peer")            return 3; // Gives Peer the middle priority
        if (s == "ImportantPerson") return 2; // Gives ImportantPerson the second-lowest priority

        return 1; // Gives OtherPerson the lowest priority
    } // Ends the rankFor method


    // The following keyFor method is from the original code generated by Claude
    // It converts a date from MM-DD-YYYY into YYYYMMDD so newer dates have larger values
    static int keyFor(const string& d) { // Starts the date conversion

        int month = stoi(d.substr(0, 2)); // Extracts and converts the month to an integer
        int day = stoi(d.substr(3, 2));   // Extracts and converts the day to an integer
        int year = stoi(d.substr(6, 4));  // Extracts and converts the year to an integer

        return year * 10000 + month * 100 + day; // Combines the values into YYYYMMDD format

    } // Ends the keyFor method

}; // Ends the Email class

// The following MaxHeap class is based on the original code generated by Claude
// The peekMax and removeMax methods were revised with help from ChatGPT
// This class implements the list-based MaxHeap that stores and prioritizes Email objects
class MaxHeap { // Starts the MaxHeap class

private: // Makes the following data members and helper methods accessible only inside the MaxHeap class

    Email* items; // Points to the dynamically allocated array that stores the Email objects
    int count; // Stores the current number of emails in the heap
    int capacity; // Stores the maximum number of emails the current array can hold


    // The following parentOf method is from the original code generated by Claude
    // It calculates the index of a node's parent in the heap
    int parentOf(int i) const { // Starts the parent index calculation method

        return (i - 1) / 2; // Calculates and returns the parent index of the current heap position

    } // Ends the parentOf method

    // The following leftOf method is from the original code generated by Claude
    // It calculates the index of a node's left child in the heap
    int leftOf(int i) const { // Starts the left-child index calculation method

        return 2 * i + 1; // Calculates and returns the left-child index

    } // Ends the leftOf method

    // The following rightOf method is from the original code generated by Claude
    // It calculates the index of a node's right child in the heap
    int rightOf(int i) const { // Starts the right-child index calculation method

        return 2 * i + 2; // Calculates and returns the right-child index

    } // Ends the rightOf method

    // The following swapItems method is from the original code generated by Claude
    // It swaps two Email objects stored at different positions in the heap
    void swapItems(int a, int b) { // Starts the method that swaps two heap entries

        Email temp = items[a]; // Temporarily stores the Email located at index a
        items[a] = items[b]; // Copies the Email at index b into index a
        items[b] = temp; // Copies the original Email from index a into index b

    } // Ends the swapItems method

    // The following grow method is from the original code generated by Claude
    // It doubles the heap capacity when the current dynamic array becomes full
    void grow() { // Starts the method that increases the heap's storage capacity

        int newCapacity = capacity * 2; // Calculates a new capacity that is twice the current capacity
        Email* bigger = new Email[newCapacity]; // Allocates a larger dynamic array for the Email objects

        for (int i = 0; i < count; i++) { // Loops through every Email currently stored in the heap
            bigger[i] = items[i]; // Copies the current Email into the same position in the larger array
        } // Ends the loop that copies the stored Email objects

        delete[] items; // Frees the memory used by the old dynamic array
        items = bigger; // Updates the heap pointer so it points to the new larger array
        capacity = newCapacity; // Updates the stored capacity to match the new array size

    } // Ends the grow method

    // The following siftUp method is from the original code generated by Claude
    // It moves a newly inserted Email upward until the MaxHeap priority order is restored
    void siftUp(int i) { // Starts the method that moves an Email upward through the heap

        while (i > 0) { // Continues while the current Email is not already at the root

            int parent = parentOf(i); // Finds the index of the current Email's parent

            if (items[i].hasHigherPriorityThan(items[parent])) { // Checks whether the current Email has higher priority than its parent
                swapItems(i, parent); // Swaps the current Email with its parent
                i = parent; // Updates the current index to the parent's old position

            } else { // Runs if the current Email is already in the correct heap position
                break; // Stops moving the Email upward because the MaxHeap order is correct

            } // Ends the priority comparison
        } // Ends the sift-up loop
    } // Ends the siftUp method

    // The following siftDown method is from the original code generated by Claude
    // It moves an Email downward until the MaxHeap priority order is restored
    void siftDown(int i) { // Starts the method that moves an Email downward through the heap

        while (true) { // Continues until the Email reaches its correct position
            int left = leftOf(i); // Finds the index of the current Email's left child
            int right = rightOf(i); // Finds the index of the current Email's right child
            int largest = i; // Initially assumes the current Email has the highest priority

            if (left < count && items[left].hasHigherPriorityThan(items[largest])) { // Checks whether the left child exists and has higher priority
                largest = left; // Marks the left child as the highest-priority Email among those checked
            } // Ends the left-child comparison

            if (right < count && items[right].hasHigherPriorityThan(items[largest])) { // Checks whether the right child exists and has higher priority
                largest = right; // Marks the right child as the highest-priority Email among those checked
            } // Ends the right-child comparison

            if (largest == i) { // Checks whether the current Email is already higher priority than both children
                break; // Stops the loop because the MaxHeap order has been restored
            } // Ends the check for the correct heap position

            swapItems(i, largest); // Swaps the current Email with the higher-priority child
            i = largest; // Updates the current index to continue checking farther down the heap
        } // Ends the sift-down loop
    } // Ends the siftDown method

public: // Makes the following constructor and heap operations accessible outside the MaxHeap class

    // The following MaxHeap constructor is from the original code generated by Claude
    // It creates an empty MaxHeap with an initial capacity of 16 Email objects
    MaxHeap() : count(0), capacity(16) { // Initializes the heap count to 0 and starting capacity to 16
        items = new Email[capacity]; // Allocates the initial dynamic array used to store Email objects
    } // Ends the MaxHeap constructor

    // The following MaxHeap destructor is from the original code generated by Claude
    // It releases the dynamic memory used by the heap when the MaxHeap object is destroyed
    ~MaxHeap() { // Starts the MaxHeap destructor
        delete[] items; // Frees the dynamic array that stores the Email objects
    } // Ends the MaxHeap destructor

    // The following deleted copy constructor is from the original code generated by Claude
    // It prevents a MaxHeap object from being copied because the class owns dynamic memory
    MaxHeap(const MaxHeap&) = delete; // Prevents creation of a MaxHeap by copying another MaxHeap

    // The following deleted assignment operator is from the original code generated by Claude
    // It prevents one MaxHeap object from being assigned to another
    MaxHeap& operator=(const MaxHeap&) = delete; // Prevents assignment between MaxHeap objects

    // The following size method is from the original code generated by Claude
    // It returns the current number of emails stored in the heap
    int size() const { // Starts the method that returns the heap size
        return count; // Returns the number of Email objects currently stored
    } // Ends the size method

    // The following insert method is from the original code generated by Claude
    // It adds a new Email to the MaxHeap and restores the required priority order
    void insert(const Email& e) { // Starts the method that inserts a new Email

        if (count == capacity) { // Checks whether the current dynamic array is full
            grow(); // Doubles the storage capacity when there is no remaining space
        } // Ends the capacity check

        items[count] = e; // Places the new Email in the next unused heap position
        siftUp(count); // Moves the new Email upward until the MaxHeap order is restored
        count++; // Increases the stored number of emails by one

    } // Ends the insert method

    // The following peekMax method is based on the original code generated by Claude
    // It was revised to safely return nullptr when the heap is empty, with help from ChatGPT
    // It provides read-only access to the highest-priority Email without removing it
    const Email* peekMax() const { // Starts the method that accesses the highest-priority Email

        if (count == 0) { // Checks whether the MaxHeap contains no emails
            return nullptr; // Returns nullptr because there is no Email to access
        } // Ends the empty-heap check

        return &items[0]; // Returns a read-only pointer to the highest-priority Email

    } // Ends the peekMax method

    // The following removeMax method is based on the original code generated by Claude
    // It was revised to avoid unnecessary heap operations when removing the final Email, with help from ChatGPT
    // It removes the highest-priority Email and restores the MaxHeap order when needed
    void removeMax() { // Starts the method that removes the root Email

        if (count == 0) { // Checks whether the heap is already empty
            return; // Ends the method because there is no Email to remove
        } // Ends the empty-heap check

        count--; // Decreases the number of stored emails by one

        if (count > 0) { // Checks whether any emails remain after removing the highest-priority Email
            items[0] = items[count]; // Moves the last Email in the heap into the root position
            siftDown(0); // Restores the MaxHeap order by moving the new root downward when needed
        } // Ends the check for remaining emails

    } // Ends the removeMax method
}; // Ends the MaxHeap class

// The following EmailQueue class is based on the original code generated by Claude
// The showNext, markRead, and showCount methods were revised with help from ChatGPT
// This class manages the CEO's inbox by using a MaxHeap as the priority queue
class EmailQueue { // Starts the EmailQueue class

private: // Makes the following data members accessible only inside the EmailQueue class

    MaxHeap heap; // Stores the unread emails in priority order using the MaxHeap
    int nextSequence; // Stores the sequence number that will be assigned to the next incoming email

public: // Makes the following constructor and queue operations accessible outside the EmailQueue class

    // The following EmailQueue constructor is from the original code generated by Claude
    // It creates an empty email queue and starts the sequence counter at 0
    EmailQueue() : nextSequence(0) {} // Initializes the arrival sequence counter to 0 and ends the constructor

    // The following addEmail method is from the original code generated by Claude
    // It creates a new Email object and inserts it into the MaxHeap
    void addEmail(const string& sender, const string& subject, const string& date) { // Starts the method that adds a new email

        Email e(sender, subject, date, nextSequence); // Creates a new Email object using the provided data and current sequence number
        nextSequence++; // Increases the sequence number so the next email receives a different arrival order
        heap.insert(e); // Inserts the new Email into the MaxHeap according to its priority

    } // Ends the addEmail method

    // The following showNext method is based on the original code generated by Claude
    // It was revised to use the safer peekMax method, private Email getter methods,
    // and newline characters instead of unnecessary stream flushes, with help from ChatGPT
    // It displays the highest-priority unread Email without removing it from the queue
    void showNext() const { // Starts the method that displays the next Email to read

        const Email* e = heap.peekMax(); // Gets a read-only pointer to the highest-priority Email

        if (e == nullptr) { // Checks whether there are no unread emails
            cout << "There are no emails to read." << '\n' << '\n'; // Displays the empty-queue message without unnecessary stream flushing
            return; // Ends the method because there is no Email to display
        } // Ends the empty-queue check

        cout << "Next email:" << '\n'; // Displays the heading and moves to the next line
        cout << "\tSender: " << e->getSender() << '\n'; // Displays the sender using the Email getter
        cout << "\tSubject: " << e->getSubject() << '\n'; // Displays the subject using the Email getter
        cout << "\tDate: " << e->getDate() << '\n' << '\n'; // Displays the date followed by a blank line

    } // Ends the showNext method

    // The following markRead method is based on the original code generated by Claude
    // It was revised to display a message when READ is used on an empty queue, with help from ChatGPT
    // It removes the highest-priority unread Email after the CEO has read it
    void markRead() { // Starts the method that marks the next Email as read

        if (heap.peekMax() == nullptr) { // Checks whether there are no unread emails

            cout << "No emails to read." << '\n' << '\n'; // Tells the user there is no Email to remove

            return; // Ends the method because the queue is empty

        } // Ends the empty-queue check

        heap.removeMax(); // Removes the highest-priority unread Email without displaying it

    } // Ends the markRead method

    // The following showCount method is based on the original code generated by Claude
    // It was revised to use correct singular output, avoid unnecessary stream flushes,
    // and store the heap size once for clearer and more efficient count handling, with help from ChatGPT
    // It displays the current number of unread emails
    void showCount() const { // Starts the method that displays the unread-email count

        int unreadCount = heap.size(); // Stores the current number of unread emails so the heap size is only retrieved once

        if (unreadCount == 1) { // Checks whether exactly one unread Email remains

            cout << "There is 1 email to read." << '\n' << '\n'; // Displays grammatically correct singular output

        } else { // Runs when there are zero or multiple unread emails

            cout << "There are " << unreadCount << " emails to read." << '\n' << '\n'; // Displays the plural unread-email count

        } // Ends the singular/plural output check

    } // Ends the showCount method
}; // Ends the EmailQueue class

// The following CommandProcessor class is based on the original code generated by Claude
// Its input handling was revised to support both test files and standard input, with help from ChatGPT
// This class reads commands and sends each command to the EmailQueue
class CommandProcessor { // Starts the CommandProcessor class

private: // Makes the following data member and helper methods accessible only inside the CommandProcessor class

    EmailQueue inbox; // Stores and manages the CEO's unread emails using an EmailQueue object

    // The following trim method is from the original code generated by Claude
    // It removes spaces, tabs, carriage returns, and newline characters from both ends of a string
    static string trim(const string& s) { // Starts the method that removes extra whitespace

        size_t start = 0; // Stores the index of the first non-whitespace character
        size_t end = s.size(); // Stores the position just after the last character in the string

        while (start < end && (s[start] == ' ' || s[start] == '\t' || // Checks whether the first character is a space or tab
                               s[start] == '\r' || s[start] == '\n')) { // Also checks for carriage-return or newline characters
            start++; // Moves the starting position forward past the whitespace character
        } // Ends the loop that removes whitespace from the beginning of the string

        while (end > start && (s[end - 1] == ' ' || s[end - 1] == '\t' || // Checks whether the last character is a space or tab
                               s[end - 1] == '\r' || s[end - 1] == '\n')) { // Also checks for carriage-return or newline characters
            end--; // Moves the ending position backward past the whitespace character
        } // Ends the loop that removes whitespace from the end of the string

        return s.substr(start, end - start); // Returns only the portion of the string without surrounding whitespace

    } // Ends the trim method

    // The following handleEmail method is from the original code generated by Claude
    // It separates the sender, subject, and date fields from an EMAIL command
    void handleEmail(const string& args) { // Starts the method that processes the contents of an EMAIL command

        size_t firstComma = args.find(','); // Finds the location of the first comma in the EMAIL information
        size_t lastComma = args.rfind(','); // Finds the location of the last comma in the EMAIL information

        if (firstComma == string::npos || firstComma == lastComma) { // Checks whether the required commas are missing or invalid
            return; // Ignores the malformed EMAIL command and ends the method
        } // Ends the EMAIL format validation

        string sender = trim(args.substr(0, firstComma)); // Extracts and trims the sender category before the first comma
        string subject = trim(args.substr(firstComma + 1, lastComma - firstComma - 1)); // Extracts and trims the subject between the commas
        string date = trim(args.substr(lastComma + 1)); // Extracts and trims the date after the last comma

        inbox.addEmail(sender, subject, date); // Creates and inserts the new Email into the priority queue

    } // Ends the handleEmail method

public: // Makes the following command-processing method accessible outside the CommandProcessor class

    // The following processInput method is based on the original processFile method generated by Claude
    // It was revised to accept an input stream so commands can come from either a test file or standard input, with help from ChatGPT
    void processInput(istream& input) { // Starts the method that processes commands from an input stream

        string line; // Creates a string that will store one command line at a time

        while (getline(input, line)) { // Reads each command from the selected input stream until the end

            line = trim(line); // Removes unnecessary whitespace from the beginning and end of the command

            if (line.empty()) { // Checks whether the current line contains no command
                continue; // Skips the empty line and moves to the next input line
            } // Ends the empty-line check

            if (line.compare(0, 6, "EMAIL ") == 0) { // Checks whether the current command begins with "EMAIL "
                handleEmail(line.substr(6)); // Sends the information after "EMAIL " to the EMAIL command handler

            } else if (line == "NEXT") { // Checks whether the current command is NEXT
                inbox.showNext(); // Displays the highest-priority unread Email without removing it

            } else if (line == "READ") { // Checks whether the current command is READ
                inbox.markRead(); // Removes the highest-priority unread Email from the queue

            } else if (line == "COUNT") { // Checks whether the current command is COUNT
                inbox.showCount(); // Displays the current number of unread emails

            } // Ends the command-selection structure

        } // Ends the loop that reads commands from the input stream
    } // Ends the processInput method
}; // Ends the CommandProcessor class

// The following main function is based on the original code generated by Claude
// It was revised to support both a command-line test file and standard input, with help from ChatGPT
int main(int argc, char* argv[]) { // Starts the main function

    CommandProcessor processor; // Creates the CommandProcessor object that will handle the input commands

    if (argc > 1) { // Checks whether a test-file name was provided

        ifstream inputFile(argv[1]); // Opens the test file provided on the command line

        if (!inputFile) { // Checks whether the file opened successfully
            cout << "Unable to open file." << '\n'; // Displays an error when the file cannot be opened
            return 1; // Ends the program because the requested file could not be opened
        } // Ends the file-open check

        processor.processInput(inputFile); // Processes commands from the test file

    } else { // Runs when no filename was provided
        processor.processInput(cin); // Processes commands from standard input
    } // Ends the input-method selection

    return 0; // Ends the program successfully

} // Ends the main function